version: '3'

services:
  docker-monitor:
    image: docker-monitor:latest
    container_name: docker-monitor
    ports:
      - "8088:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge
